name: Sync index.html to Toxico (Verbose)

on:
  push:
    paths:
      - "index.html"   # trigger เมื่อแก้ไขไฟล์นี้

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Show current branch
        run: |
          echo "Current branch: $GITHUB_REF"

      - name: Clone Repo B (Toxico)
        run: |
          echo "Cloning repo B..."
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ntwkkm/Toxico.git
          echo "Clone finished."
          
      - name: Copy index.html
        run: |
          cp index.html Toxico/
          ls -l Toxico/
          echo "index.html copied to repo B folder."

      - name: Commit and Push to Repo B
        run: |
          cd Toxico
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Sync index.html from ntwkkm.github.io"
            git push
            echo "Push to repo B successful ✅"
          fi

      - name: Final Log
        run: echo "Workflow finished. Check repo B (Toxico) for updated index.html"
